name: Telegram PDF to GitHub

on:
  repository_dispatch:
    types: [telegram-pdf]

jobs:
  process-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Download PDF
        run: |
          mkdir -p pdfs
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@users.noreply.github.com"
          git pull --rebase
          
          CLEAN_FILENAME="${{ github.event.client_payload.file_name }}"
          PDF_FILENAME="pdfs/${CLEAN_FILENAME}"
          
          echo "Downloading from: ${{ github.event.client_payload.pdf_url }}"
          echo "Saving as: $PDF_FILENAME"
          
          # Download PDF (works for both Telegram files and direct links)
          curl -L --progress-bar "${{ github.event.client_payload.pdf_url }}" -o "$PDF_FILENAME"
          
          if [ -f "$PDF_FILENAME" ]; then
            echo "✅ PDF downloaded successfully"
            git add .
            git commit -m "Add PDF: $CLEAN_FILENAME"
            git pull --rebase
            git push
            echo "✅ PDF committed successfully"
          else
            echo "❌ Failed to download PDF"
            exit 1
          fi

      - name: Send completion notification
        run: |
          CHAT_ID="${{ github.event.client_payload.chat_id }}"
          FILENAME="${{ github.event.client_payload.file_name }}"
          
          if [ -n "$CHAT_ID" ]; then
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d "chat_id=$CHAT_ID" \
              -d "text=✅ **Upload Complete!**\n\n• File: $FILENAME\n• Status: Successfully uploaded!\n\n📁 View: https://github.com/${{ github.repository }}/tree/main/pdfs" \
              -d "parse_mode=Markdown"
          fi
