name: Telegram PDF to GitHub

on:
  repository_dispatch:
    types: [telegram-pdf]

jobs:
  process-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Download PDF with sequential numbering
        run: |
          # Create pdfs directory
          mkdir -p pdfs
          
          # PULL LATEST CHANGES FIRST to avoid conflicts
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@users.noreply.github.com"
          git pull
          
          # Get the next available number (check all existing files)
          LAST_NUMBER=$(find pdfs -name "*.pdf" | grep -oE '[0-9]+' | sort -n | tail -1)
          if [ -z "$LAST_NUMBER" ]; then
            NEXT_NUMBER=0
          else
            NEXT_NUMBER=$((LAST_NUMBER + 1))
          fi
          
          # Format as 4-digit number (0000, 0001, 0002, etc.)
          FORMATTED_NUMBER=$(printf "%04d" $NEXT_NUMBER)
          PDF_FILENAME="pdfs/${FORMATTED_NUMBER}.pdf"
          
          echo "Next file number: $FORMATTED_NUMBER"
          echo "Saving as: $PDF_FILENAME"
          
          # Download the PDF
          curl -L --progress-bar "${{ github.event.client_payload.pdf_url }}" -o "$PDF_FILENAME"
          
          # Check if download was successful
          if [ -f "$PDF_FILENAME" ]; then
            echo "✅ PDF downloaded successfully as $PDF_FILENAME"
            echo "File size: $(ls -la "$PDF_FILENAME")"
            
            # Add, commit and push
            git add .
            git commit -m "Add PDF: ${FORMATTED_NUMBER}.pdf"
            git pull --rebase  # Pull any new changes before pushing
            git push
            
            echo "✅ PDF committed as ${FORMATTED_NUMBER}.pdf"
          else
            echo "❌ Failed to download PDF"
            exit 1
          fi
